// test/gates.mjs — canonical gate registry + per-gate metadata for run-all.mjs.
//
// Single source of truth for the pass/fail gate list (test/ also holds libs and rainy-day
// scripts that are NOT gates — see run-all.mjs header). `npm test` runs AFFECTED gates only:
// run-all.mjs computes each gate's transitive import closure live from disk and intersects it
// with your working-tree changes, so a physics edit runs the physics gates, a prop-slider tweak
// runs the prop gates, and a skybox edit runs nothing. `npm run test:all` runs everything.
//
// The fields here are the human- + agent-readable layer:
//   subsystem  coarse label for the selection report + for hand-picking `--only` sets.
//   cost       'fast' = no network worldgen (physics / props / isolated primitive math);
//              'heavy' = full road/terrain/water generation. Advisory only (rough, not measured);
//              it warns when an affected set will be slow. Selection does NOT use cost.
//   extraDeps  repo-relative paths a gate depends on but does NOT `import` (text mirrors, JSON
//              assets) — the import-closure can't see these, so list them or the gate won't be
//              selected when that file changes. Treated as exact-file triggers (their own imports
//              are NOT followed — the coupling is to the file's literal content).
//
// Adding a gate: add an entry here AND write test/<file>. Keep this list in run order.

export const GATES = [
  { file: 'arc-router.mjs', subsystem: 'road', cost: 'fast', extraDeps: [],
    desc: 'arc-primitive router valid-by-construction: reaches goal, detours peaks, min-radius, determinism (search-time now report-only)' },
  { file: 'road-dequantize.mjs', subsystem: 'road', cost: 'fast', extraDeps: [],
    desc: 'BUG-16+FEAT-20 de-quantize refit: shortcut straightens the bow, κ-filter clothoids, switchbacks preserved, endpoint-exact (timing report-only)' },
  { file: 'road-minradius.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'BUG-12: DENSE realized centerline min-radius the ribbon sweeps (incl. capture fixtures) — the fold metric' },
  { file: 'centerline-curvature.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'EXACT per-primitive min-radius + two-center invariance (construction-level, complements road-minradius realized geometry)' },
  { file: 'defect-b-grade.mjs', subsystem: 'road', cost: 'fast', extraDeps: [],
    desc: 'smoothGradeInPlace window-invariance + grade-flip collapse + ramp-preserved (defect B)' },
  { file: 'invariance.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'two-center network invariance: arcS + gradeY stable across streaming windows' },
  { file: 'road-band-coverage.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'Mechanism B: R-scaled band covers the disc — runs do not drop out on fly-over (hit+gradeY invariant)' },
  { file: 'restream-invariance.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'same-instance re-stream (cache reuse) invariance — within-cell skip preserves cache; drive-in == fresh' },
  { file: 'ribbon-carve.mjs', subsystem: 'terrain', cost: 'heavy', extraDeps: [],
    desc: 'synthetic ribbon↔carve agreement (dump-free; replaced seam-grade.mjs)' },
  { file: 'road-smoothness.mjs', subsystem: 'terrain', cost: 'heavy', extraDeps: [],
    desc: 'collision surface has no invisible step the visual ribbon lacks (carve continuity)' },
  { file: 'road-tunnel.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'FEAT-40: taut-string summit cut fires on seed 6, bores stay driveable (grade/C0), physics floor vs raw-hill skin diverge only in-bore, spans window-invariant' },
  { file: 'shoulder-lateral-continuity.mjs', subsystem: 'terrain', cost: 'heavy', extraDeps: [],
    desc: 'BUG-15: carve cross-section is C0 across the shoulder edge (no camber-tilt cliff → no airborne/slam in hairpins)' },
  { file: 'road-fill-support.mjs', subsystem: 'terrain', cost: 'heavy', extraDeps: [],
    desc: 'BUG-15 (fill): physics footprint matches the mesh embankment extent — car does not drop through a raised fill shoulder' },
  { file: 'carve-mesh-smoothness.mjs', subsystem: 'terrain', cost: 'heavy', extraDeps: [],
    desc: 'QUAL-07 net: REAL _buildCarveTable whole-surface has no catastrophic spikes/tearing (spike% + worst 2nd-diff bounded vs baseline)' },
  { file: 'road-apex-sliver.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'BUG-21: no off-road sliver at a shared hairpin anchor (radial end-fallback) — no jolt crossing run boundaries' },
  { file: 'replay-selftest.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'capture↔replay round-trip (Phase 4 place path) — guards src/capture.js + replay.mjs tooling' },
  { file: 'prop-shadow-alignment.mjs', subsystem: 'props', cost: 'fast', extraDeps: ['src/main.js', 'src/terrain.js'],
    desc: 'PERF-07: bake-camera UV == terrain-sampler UV per axis (the twice-shipped mirror bug), shear == sun-ray ground hit, prop ring ⊂ atlas' },
  { file: 'route-worker-sync.mjs', subsystem: 'road', cost: 'fast', extraDeps: ['src/road-carve.js', 'src/road-worker.js'],
    desc: 'PERF-03 WS-A: worker routing copy (road-worker.js ROAD_WORKER_SOURCE) byte-identical to road-carve.js canonical' },
  { file: 'route-bundle-parity.mjs', subsystem: 'road', cost: 'heavy',
    extraDeps: ['data/route-cache-default.json.gz', 'data/route-cache-region.json.gz'],
    desc: 'QUAL-14/PERF-26: both bundled route caches == live router output, region delta disjoint from base, and the pair covers the story warm band (regenerate BOTH on any router change)' },
  { file: 'route-merge.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'FEAT-10: no collinear duplicates + connectivity (graph emits each edge once)' },
  { file: 'crossing-classifier.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'FEAT-07/08/11/13: bounded crossing classifier == brute force (feeds FEAT-19 carve widening) + once-per-build identity' },
  { file: 'road-graph.mjs', subsystem: 'road', cost: 'fast', extraDeps: [],
    desc: 'FEAT-13 v2: Delaunay/Urquhart primitives — empty-circumcircle, Urquhart⊇MST (connected), order-invariant' },
  { file: 'graph-topology.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'FEAT-13 v2: blue-noise + Urquhart: reachability (known-accepted 78% red, see BUG-35), window-invariance, direction variety, step-free surface, junction-at-grade' },
  { file: 'graph-cull-radius-invariance.mjs', subsystem: 'road', cost: 'heavy', extraDeps: [],
    desc: 'BUG-25: crossing cull is render-radius- + approach-history-invariant (320 m vs 1500 m edge sets agree; drive-out-and-back reproduces the network)' },
  { file: 'props.mjs', subsystem: 'props', cost: 'fast', extraDeps: [],
    desc: 'FEAT-06: prop geometry sanity + scatter determinism/window-invariance + slot accounting' },
  { file: 'prop-road-clearance.mjs', subsystem: 'props', cost: 'fast', extraDeps: [],
    desc: 'BUG-23: no hard-collidable prop (centre-or-overhang) on the road footprint (inflated keep-out)' },
  { file: 'rock-collision-proxy.mjs', subsystem: 'props', cost: 'fast', extraDeps: [],
    desc: 'BUG-22: ROCK hard-contact sphere proxy fits the visible surface (no overshoot air-gap → no spurious sideways shove)' },
  { file: 'rock-collision-mesh.mjs', subsystem: 'props', cost: 'fast', extraDeps: [],
    desc: 'BUG-22c: BOULDERS collide vs their actual triangle mesh (exact visible surface, no sphere overshoot)' },
  { file: 'box3d-determinism-gate.mjs', subsystem: 'physics', cost: 'fast',
    extraDeps: ['vendor/box3d/dist/box3d.mjs', 'test/box3d-determinism.expected'],
    desc: 'FEAT-48: the physics engine is bit-deterministic — 10k-step state hash reproduces in-process and matches the recorded Phase 0 expectation (engine/bindings drift alarm)' },
  { file: 'penetration-failsafe.mjs', subsystem: 'physics', cost: 'fast', extraDeps: [],
    desc: 'BUG-24: catastrophic-penetration failsafe fires only on true tunnels (depth>2·wheelRadius = wheel fully swallowed), not resolvable deep contact — no teleport on the shoulder step or in the sub-2R band' },
  { file: 'body-contact-energy.mjs', subsystem: 'physics', cost: 'fast', extraDeps: [],
    desc: 'BUG-27: hard body slams honor params.bodyRestitution without amplifying it (sampled-once bias, accumulated-impulse solver, tamed Baumgarte) — no phantom spin/launch, no energy gain, rest stable' },
  { file: 'drivetrain-climb.mjs', subsystem: 'physics', cost: 'fast', extraDeps: [],
    desc: 'FEAT-23: auto-trans + torque-converter climbs 20–30% grades from a stop, no drive/brake oscillation; accel tapers; 4-gear progression, no shift hunting' },
  { file: 'wheel-multicontact-friction.mjs', subsystem: 'physics', cost: 'fast', extraDeps: [],
    desc: 'BUG-38: Pacejka tire friction is evaluated ONCE per wheel against the support surface — a 2nd contact (wall/prop/ramp) adds only push-out via _hubNormalXZ, never re-applied grip; no double-counted cornering/drive force when a wheel straddles ground + obstacle' },
  { file: 'mission-network.mjs', subsystem: 'story', cost: 'heavy', extraDeps: [],
    desc: 'story missions route ONLY over the post-cull registered network (raw Urquhart has ~15% phantom edges), use the registered centerline object, and edgeParData reports the registered runKey either way route; plus the BUG-41 drift alarm — par prices the routed polyline while the world carves runProfile().gradeY, and that WONTFIX only holds while the two agree in the run INTERIOR and disagree solely in the junction end bands' },
  { file: 'world-determinism.mjs', subsystem: 'story', cost: 'heavy',
    extraDeps: ['src/main.js', 'src/story.js'],
    desc: 'THE SEED IS AN ABSOLUTE DETERMINISM MACHINE (owner, 2026-08-10). Three links, all asserted: the SPAWN is a pure function of the seed even though it is resolved by probing the streamed network (5 seeds x prior streaming histories — cold, idled at spawn, drove 3 km away, and for a subset a warmed off-centre 1500 m region); the region CENTRE is that spawn, because story entry reseats on both branches before capturing it, so where the player was standing cannot reach worldgen; and what the region CONTAINS at a given centre — registered graph, POI candidate pool, roster, newspaper customers — is identical from any history, which is the link BUG-25 window-bounded cull flips would break. Plus the floor: the same (seed, centre) built twice is byte-identical. ~4.5 min — seed count and window are trimmed deliberately and the trims are stated in the file' },
  { file: 'story-poi.mjs', subsystem: 'story', cost: 'heavy', extraDeps: ['src/terrain.js'],
    desc: 'FEAT-46 story POIs: a job taken from a POI starts AT that POI on every roll incl. regenerate; the ROAD SURFACE is bit-identical with and without the lay-by pads (free roam == story mode — the ratified rule), placement is downstream of routing and window-invariant (keyed off graph edges; the region clip is a post-filter, never a reject test), pads are flat + fully carved, and the on-water / junction / earthwork-cap rejects bite; FEAT-53: single-offer rule (one cached job per POI per day, accept consumes, invalidatePlan clears) and the do-over lockout (regenerate/retry inert on paid jobs, live on Quick Job)' },
  { file: 'par-oracle.mjs', subsystem: 'story', cost: 'fast', extraDeps: ['src/main.js'],
    desc: 'FEAT-29 par oracle: SM-INV-2 (par never reads the car), determinism, independent time-marched check, SIGNED grade (downhill faster), curvature monotonicity, mid-edge arc-range splitting, junction penalty, spawn-heading convention' },
  { file: 'gps-route.mjs', subsystem: 'story', cost: 'fast', extraDeps: ['src/main.js'],
    desc: 'FEAT-39 GPS assist route bake: travel order (reversed edges + partial first/last ranges), turn sign (+ve = right) + the straight deadband, windowed progress monotonic + full-scan re-acquire, 3-D arc from gradeAt' },
  { file: 'day-clock.mjs', subsystem: 'story', cost: 'fast', extraDeps: [],
    desc: 'FEAT-47 day clock: SM-INV-12 flag-gate (blinks off ⇒ attenuation ≡ 1, eyelids ≡ 0), pinned runState advances only at midnight/sleep boundaries, sky pushes ride the quant ladder (~11/min not ~3600), energy ladder 12/14/16 h with sleep debt to a −8 floor, tired signal once per crossing, coffee +5/−3 settled-then-clamped at wake, r(0.5)=2.0 (avg site = full in 8 h) and r(1)=2·r(0)' },
  { file: 'economy.mjs', subsystem: 'story', cost: 'fast', extraDeps: [],
    desc: 'FEAT-53 economy spine: SM-INV-4 payout anchors (1.2→0, par→k·par·tier exact, 0.8→2×, cap at ≤0.60) + zero floor over degenerate inputs, parBase ∝ par (no tiny-job farming), SM-INV-14 points 1/½/0 monotone in elapsed, dayTier steps clamped, rank thresholds tighten with day but B always contains par, terms locked at accept (the 1 a.m. feature), runEconomy sibling of runState, economy.js imports nothing' },
  { file: 'paper-route.mjs', subsystem: 'story', cost: 'fast', extraDeps: [],
    desc: 'FEAT-61 paper route scoring: the accuracy law q(0)=1 → q(R)=0.30 linear with the rim cliff OUTSIDE, PARTIAL ROUTES PAY (1-of-9 letters D and still banks one paper — this mission is the income floor), flat rate anchored k·par·tier·paperW/customers so a perfect route at par pays 0.60× the margin line, expediency bonus unreachable without full coverage and capped at bonusMax, per-axis rank on coverage×accuracy and never the clock, ladder 4→9→12→15 advancing only on a perfect route, spares 100%→30%, deadline = par×tolerance, SM-INV-4 untouched (payoutFor/gradeRun neither called nor imported) with settleFlat sharing one wallet + pointsFor, degenerate inputs pay 0 not NaN' },
  { file: 'paper-tour.mjs', subsystem: 'story', cost: 'heavy', extraDeps: ['src/poi.js', 'src/mission.js'],
    desc: 'FEAT-61 the paper ROUTE on a real network: a tour plans at every rung of the 4→9→12→15 ladder, ONE par over the whole thing (SM-INV-2) growing monotonically but not proportionally with the route, a lower tier is a PREFIX of a higher one (SM-INV-12 — the tier picks who is on the route, never what exists), a stop is an (edge, arc) POINT spliced into the graph so the route reaches the porch and carries on whichever way is shorter — never snapped to a junction (5 of 6 customers unapproached) and never a whole street driven end to end (ran past the porch to finish the tarmac, then turned around), 2-opt shortens the finished order, every segment names a registered edge, the driven polyline stays inside the region wall, deadlineFor(par) > par at every rung, degenerate inputs return null rather than a broken route — PLUS a whole route driven end to end through PaperRouteSystem: park at Larry\'s → offer → staging (the clock does NOT start on the pad) → leaving the threshold starts it → A PAPER DEAD CENTRE ON A ROUTE CUSTOMER CREDITS THEM at q=1.00 and moves the counter (the mechanic owner-reported broken 2026-08-09), a second paper on the same porch is spent not double-counted, a paper on a customer who is not on this route scores nothing, the last porch ends the route, and a perfect route letters S, pays through settleFlat and earns the next rung' },
  { file: 'paper-reroute.mjs', subsystem: 'story', cost: 'heavy', extraDeps: ['src/poi.js', 'src/mission.js'],
    desc: 'FEAT-63 the GPS re-plan: ONE ALGORITHM, TWO DRIVERS — planTour and a fully-drained planTourJob return identical routes, and so does a job driven one next() at a time, so the sliced path can never quietly become a second planner; the top rung\'s job is ~48 slices (a generator that yielded once would pass every other check here while being useless to the frame pump); a CANCELLED job hands its leased Held-Karp tables back through the generator\'s finally, so the next plan is still exact — the silent corruption the lease exists to prevent; a re-plan covers exactly the undelivered set and never re-adds a delivered customer; from a point ON the line it is never longer than carrying on (2% slack, because the DP minimises the planner\'s mixed chord/arc graph metric while distance is computePar\'s true arc — a hairline overshoot is a metric artefact, a large one means the optimiser was handed the wrong graph); and from a customer at the FAR END — the ignored-the-GPS case the whole feature exists for — it BEATS the stale line by >5% rather than merely tying it; the contract re-prices identically after a re-plan has run (SM-INV-2, checked through the shared table pool, which is the one thing that could actually move par); a one-stop re-plan (the last porch, Held-Karp skipped entirely) still routes' },
  { file: 'camp-zones.mjs', subsystem: 'story', cost: 'fast', extraDeps: [],
    desc: 'FEAT-45 camping zones: pure f(seed, cell, params) — determinism, two-centre window-invariance, region clip is a post-filter (kept == raw grid), GLOBAL density 15–25% on seeds 1/6/7/42 (per-region is high-variance by design), 3×3 raw-scan soundness guard' },
  { file: 'camp-view.mjs', subsystem: 'story', cost: 'fast', extraDeps: [],
    desc: 'campsite view score (skylineView): ordering over synthetic landforms (summit > rim > plain, canyon/bowl ≈ nothing), a dead-flat plain is open but NOT epic (the relief term), purity under interleaved calls, translation invariance at 8 km (SM-INV-12), exact 169-sample budget per scan' },
  { file: 'lab-timing.mjs', subsystem: 'story', cost: 'fast', extraDeps: [],
    desc: 'FEAT-31 testing-lab gates: skidpad lap time + derived mu vs closed form, no phantom laps from line jitter, staged drag start (hold-still + count, false start voids, unstaged crossings inert), braking measured 100→0 in the strip corridor and voided by throttle' },
  { file: 'water-invariance.mjs', subsystem: 'water', cost: 'heavy', extraDeps: [],
    desc: 'FEAT-22/17/18: basins/saddles/ponds/streams deterministic + window-invariant; ponds rim-contained; streams descend + end at basins; submerged hook' },
  { file: 'pond-route-around.mjs', subsystem: 'water', cost: 'heavy', extraDeps: [],
    desc: 'FEAT-17: roads route AROUND ponds — setWaterNoGo filter + arc rejection: zero centerline points/nodes in any pond+skirt disc' },
  { file: 'stream-carve.mjs', subsystem: 'water', cost: 'heavy', extraDeps: [],
    desc: 'FEAT-18: stream channels cut bed+banks (C0, bounded, descending); every road×stream crossing holds road grade (ribbon-deck) with the channel notch continuous both sides' },
  { file: 'stream-bed-drape.mjs', subsystem: 'water', cost: 'heavy', extraDeps: [],
    desc: 'FEAT-25: cobble bed ribbon drapes the carved channel — dry shoulders above the waterline, center under water, deterministic' },
]
